# Generated by Django 6.0.2 on 2026-02-19 10:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('amount_iqd', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TRANSFER', 'Transfer')], default='CASH', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('total_iqd', models.PositiveIntegerField(default=0)),
                ('paid_iqd', models.PositiveIntegerField(default=0)),
                ('balance_iqd', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='members.member')),
                ('subscription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pay_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount_iqd', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TRANSFER', 'Transfer')], default='CASH', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='billing_inv_status_541249_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['balance_iqd'], name='billing_inv_balance_d28489_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='billing_inv_issue_d_0996ee_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['pay_date'], name='billing_pay_pay_dat_5a238a_idx'),
        ),
    ]
