# Generated by Django 6.0.2 on 2026-02-19 10:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('role', models.CharField(choices=[('RECEPTION', 'Reception'), ('COACH', 'Coach'), ('ACCOUNTANT', 'Accountant'), ('MANAGER', 'Manager')], max_length=30)),
                ('hire_date', models.DateField(default=django.utils.timezone.now)),
                ('base_salary_iqd', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('amount_iqd', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('TRANSFER', 'Transfer')], default='CASH', max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='payroll.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['payout_date'], name='payroll_sal_payout__734123_idx')],
            },
        ),
    ]
