# Generated by Django 6.0.2 on 2026-02-19 10:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_index=True, max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('DAILY', 'Daily (1 day)'), ('WEEKLY', 'Weekly (7 days)'), ('D10', '10 days'), ('D15', '15 days'), ('MONTHLY', 'Monthly (30 days)')], max_length=20, unique=True)),
                ('name_ar', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80)),
                ('days', models.PositiveIntegerField()),
                ('price_iqd', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('FROZEN', 'Frozen'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='members.member')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.plan')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'end_date'], name='members_sub_status_a901b1_idx'), models.Index(fields=['member', 'status'], name='members_sub_member__5333a7_idx')],
            },
        ),
    ]
